# Generated by Django 5.1.1 on 2024-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
