# Generated by Django 5.1.1 on 2024-10-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_article_discount_alter_article_cost_favorite_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='discount',
        ),
    ]
