# Generated by Django 5.1.1 on 2024-10-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_remove_article_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AddField(
            model_name='article',
            name='shopping',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупок'),
        ),
    ]
