# Generated by Django 5.1.1 on 2024-10-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_remove_favorite_product_favorite_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
